Traceback (most recent call last):
  File "/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-centos7-gcc11-opt/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-centos7-gcc11-opt/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/eos/home-y/ymaidann/eth_project/Spanet_project/SPANet/spanet/__init__.py", line 1, in <module>
    from spanet.network.jet_reconstruction import JetReconstructionModel
  File "/eos/home-y/ymaidann/eth_project/Spanet_project/SPANet/spanet/network/__init__.py", line 1, in <module>
    from spanet.network.jet_reconstruction import JetReconstructionModel
  File "/eos/home-y/ymaidann/eth_project/Spanet_project/SPANet/spanet/network/jet_reconstruction/__init__.py", line 1, in <module>
    from spanet.network.jet_reconstruction.jet_reconstruction_training import JetReconstructionTraining
  File "/eos/home-y/ymaidann/eth_project/Spanet_project/SPANet/spanet/network/jet_reconstruction/jet_reconstruction_training.py", line 4, in <module>
    import torch
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_103cuda/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/torch/__init__.py", line 218, in <module>
    from torch._C import *  # noqa: F403
ImportError: libcupti.so.11.8: cannot open shared object file: No such file or directory
